---
branches:
  - master
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - #
    - "@semantic-release/github"
    - successComment: false
      failComment: false
      assets:
        - path: build/version.dll
